// <auto-generated />
using System;
using MarathonTrainer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarathonTrainer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306152024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MarathonTrainer.Api.Models.FitnessAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ComfortablePaceMinutesPerMile")
                        .HasColumnType("REAL");

                    b.Property<string>("CrossTrainingPreferences")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentLongestRunMiles")
                        .HasColumnType("REAL");

                    b.Property<double?>("RecentRaceDistanceMiles")
                        .HasColumnType("REAL");

                    b.Property<long?>("RecentRaceTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("FitnessAssessments");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.MedicalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoctorClearance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAsthma")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHeartCondition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasKneeIssues")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPlantarFasciitis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationsAffectingHeartRate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecentInjuries")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("MedicalInfos");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceMiles")
                        .HasColumnType("REAL");

                    b.Property<string>("MedicalModifications")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetPaceMaxMinPerMile")
                        .HasColumnType("REAL");

                    b.Property<double?>("TargetPaceMinPerMile")
                        .HasColumnType("REAL");

                    b.Property<int>("TrainingWeekId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainingWeekId");

                    b.ToTable("TrainingDays");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStepBackWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalMileage")
                        .HasColumnType("REAL");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingWeeks");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentWeeklyMileage")
                        .HasColumnType("REAL");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("HeightInches")
                        .HasColumnType("REAL");

                    b.Property<int>("LongRunDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredRunDaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunningExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightLbs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.FitnessAssessment", b =>
                {
                    b.HasOne("MarathonTrainer.Api.Models.UserProfile", "UserProfile")
                        .WithOne("FitnessAssessment")
                        .HasForeignKey("MarathonTrainer.Api.Models.FitnessAssessment", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.MedicalInfo", b =>
                {
                    b.HasOne("MarathonTrainer.Api.Models.UserProfile", "UserProfile")
                        .WithOne("MedicalInfo")
                        .HasForeignKey("MarathonTrainer.Api.Models.MedicalInfo", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingDay", b =>
                {
                    b.HasOne("MarathonTrainer.Api.Models.TrainingWeek", "TrainingWeek")
                        .WithMany("TrainingDays")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingPlan", b =>
                {
                    b.HasOne("MarathonTrainer.Api.Models.UserProfile", "UserProfile")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingWeek", b =>
                {
                    b.HasOne("MarathonTrainer.Api.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingWeeks")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingPlan", b =>
                {
                    b.Navigation("TrainingWeeks");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.TrainingWeek", b =>
                {
                    b.Navigation("TrainingDays");
                });

            modelBuilder.Entity("MarathonTrainer.Api.Models.UserProfile", b =>
                {
                    b.Navigation("FitnessAssessment");

                    b.Navigation("MedicalInfo");

                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
